# Generated by Django 6.0 on 2026-01-16 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='mobno',
        ),
    ]
